# Generated by Django 5.0.3 on 2024-03-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmease_app', '0005_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='crop',
        ),
        migrations.AddField(
            model_name='solution',
            name='crop_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
