# Generated by Django 5.0.3 on 2024-03-04 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmease_app', '0006_remove_solution_crop_solution_crop_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='crop_name',
        ),
    ]
