# Generated by Django 5.0.3 on 2024-03-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmease_app', '0007_remove_solution_crop_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plant_images/')),
            ],
        ),
    ]
